matrix:
  allow_failures:
    - os: windows
os:
  - osx
  - linux
  - windows

language: rust
rust: stable

env: 
  global:
    - secure: "MDsSkJHi1W3iDvVa7Aosmx3VJHWy9GbsAybIcFzyX4xtfBoix7mhrF9XnVp0fPjk94a2KLgbUeN9exXoQacqETmg8qitl0tg0zT91h4NLls9dJ74F063OUHpmMaJBD8kjNv+rSIVeb4QY/nClB+RkDws6jMtbTC0IMU+NKiV5PKX2wA0gUykVKBW3A36j3FC3gYFcEAw4Wku7EMZblEPHH8LzOw9Z418BPdx0ivuhZ+CWWxjCPuPAJoK2i5vKVoM50DTktn4pfJJfkgSLRreAI3ZJbiVAx7L/vkZWw7SbZUIs7GZbXyAh/tnu3tiVx0MyMFasOBoGrbae/3AZlwCusE3vqnu8MfgaHCXcKi2Vo0X7Cy1fLVphsmxfizyM0QumCErww5/30vrasY/qXfkvGMV6NNbhx+AXpC02wqpqKhVaPfCDtPksN0y9vQlqjEYMj1R9DAHPHWOwRSGrrs1BxsXYVrxCja7gFz90/9HBAVzEdvN0GDIgTSTsedfytoKX5BjsMCKKWdF9UazpK1Aj36gHQgafpk1I8QFG14+mJxbHqcdcExBemN/r+VKYm0n032MmKFj3PJsiKcSVcTLlLcNsxeBnMl4l+kTVnAVuf1An1IYgI4ArPVA1SWO7waIxZmN5k8Hl3jTCEvreyf6ztYestPYKPuneHg+rOlqRxk="
  matrix:
    - $TRAVIS_NODE_VERSION=node
  

cache:
  - yarn: true
  - cargo: true

before_install:
  # Install Rust and Cargo
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
        export NVS_HOME=$ProgramData/nvs
        git clone --single-branch https://github.com/jasongin/nvs $NVS_HOME
        source $NVS_HOME/nvs.sh
        nvs --version
        nvs add $TRAVIS_NODE_VERSION && nvs use $TRAVIS_NODE_VERSION 
    else
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
        nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
    fi
  # Install global NPM packages
  - node -v
  - npm -v
  - npm install -g yarn
  - yarn global add yarn@latest
  - yarn

script: 
  - cd lib && ls
  - mkdir native && cd ..
  - ls
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then yarn upload-binary || exit 0; fi;

